name: CI

on: [push]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v1
    - name: Run Build
      run: C:\Windows\Microsoft.NET\Framework64\v4.0.30319\MSBuild.exe NewProject.sln /t:build /p:TargetFrameworkSDKToolsDirectory="C:\Program Files (x86)\Microsoft SDKs\Windows\v10.0A\bin\NETFX 4.8 Tools"
    - uses: actions/upload-artifact@master
      name: Seatbelt
      path: Seatbelt\bin\Debug\Seatbelt.exe
